services:
  agenda-db:
    container_name: agenda-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agendadb
    ports:
      - 5432:5432
    volumes:
      - agenda-db:/var/lib/postgresql/data
    networks:
      - network
    
  agenda-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${UID:-1000}
        - GROUP_ID=${GID:-1000}
    container_name: agenda-app
    image: agenda-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.env:/var/www/.env
    environment:
      - APP_ENV=local
    env_file:
      - .env
    networks:
      - network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - agenda-app
      - agenda-node
    env_file:
      - .env
    networks:
      - network

  agenda-node:
    # platform: linux/arm64/v8 #this line is optional if you are using Mac Silicon chip (M1/M2/M3)
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: agenda-node
    image: agenda-node
    ports:
    - "3000:3000"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  agenda-db:
    driver: local
